#ifndef LOCALIZATION_SOURCES
#define LOCALIZATION_SOURCES

#define LOCALIZATION_ODOM "odom"
#define LOCALIZATION_MAP "map"

#define LOCALIZATION_BASE_LINK "base_link"
#define LOCALIZATION_LIDAR_LINK "lidar_link"

#endif